### ISSUE TITLE
Unable to open DM when it contains a forwarded message

### ISSUE THREAD

**Issue by JoshStrobl** [roundedrectangle/SailDiscord#14]
On Sailcord 0.6.3, I get the following error when attempting to access a DM which contains a forwarded message from a Discord server. After requesting the sender delete the message, the DMs load again.

```
[D] unknown:0 - Using Wayland-EGL
library "libutils.so" not found
library "libdmabufheap.so" not found
library "libbase.so" not found
library "libz.so" not found
library "libcutils.so" not found
library "android.hardware.graphics.mapper@4.0.so" not found
library "libgralloctypes.so" not found
library "libhidlbase.so" not found
library "libhardware.so" not found
library "libc++.so" not found
[D] unknown:0 - Got library name:  "/usr/lib64/qt5/qml/io/thp/pyotherside/libpyothersideplugin.so"
library "libion.so" not found
[2024-12-16 23:21:46] [INFO    ] discord.client: Logging in using static token.
[2024-12-16 23:21:46] [INFO    ] discord.http: Found user agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36, build number 353815.
[2024-12-16 23:21:48] [INFO    ] discord.gateway: Connected to Gateway (Session ID: d60074594de573d14527e47d4df6a9b9).
libpng error: Read Error
[W] unknown:22 - file:///usr/share/harbour-saildiscord/qml/components/ServerListItem.qml:22:9: QML ListImage: Error decoding: file:///home/defaultuser/.cache/io.github.roundedrectangle/harbour-saildiscord/server/1071081786962088018.png: Unable to read image data
libpng error: Read Error
[W] unknown:22 - file:///usr/share/harbour-saildiscord/qml/components/ServerListItem.qml:22:9: QML ListImage: Error decoding: file:///home/defaultuser/.cache/io.github.roundedrectangle/harbour-saildiscord/server/273534239310479360.png: Unable to read image data
libpng error: Read Error
[W] unknown:22 - file:///usr/share/harbour-saildiscord/qml/components/ServerListItem.qml:22:9: QML ListImage: Error decoding: file:///home/defaultuser/.cache/io.github.roundedrectangle/harbour-saildiscord/server/155794864305471497.png: Unable to read image data
libpng error: Read Error
[W] unknown:22 - file:///usr/share/harbour-saildiscord/qml/components/ServerListItem.qml:22:9: QML ListImage: Error decoding: file:///home/defaultuser/.cache/io.github.roundedrectangle/harbour-saildiscord/user/266853529795297280.png: Unable to read image data
libpng error: Read Error
[W] unknown:22 - file:///usr/share/harbour-saildiscord/qml/components/ServerListItem.qml:22:9: QML ListImage: Error decoding: file:///home/defaultuser/.cache/io.github.roundedrectangle/harbour-saildiscord/user/453308430908915714.png: Unable to read image data
[D] unknown:0 - "PyOtherSide error: Traceback (most recent call last):\n\n  File \"/usr/share/harbour-saildiscord/python/main.py\", line 233, in set_channel\n    self.client.set_current_channel(guild, channel)\n\n  File \"/usr/share/harbour-saildiscord/python/main.py\", line 106, in set_current_channel\n    self.run_asyncio_threadsafe(self.get_last_messages(), True)\n\n  File \"/usr/share/harbour-saildiscord/python/main.py\", line 98, in run_asyncio_threadsafe\n    if result_required: return future.result(timeout)\n\n  File \"/usr/lib64/python3.8/concurrent/futures/_base.py\", line 444, in result\n    return self.__get_result()\n\n  File \"/usr/lib64/python3.8/concurrent/futures/_base.py\", line 389, in __get_result\n    raise self._exception\n\n  File \"/usr/share/harbour-saildiscord/python/main.py\", line 93, in get_last_messages\n    await send_message(m, True)\n\n  File \"/usr/share/harbour-saildiscord/python/main.py\", line 57, in send_message\n    event, args = await generate_message(message, is_history)\n\n  File \"/usr/share/harbour-saildiscord/python/main.py\", line 37, in generate_message\n    if comm.client.ensure_current_channel(message.reference.channel_id, message.reference.guild_id):\n\n  File \"/usr/share/harbour-saildiscord/python/main.py\", line 123, in ensure_current_channel\n    ccs = self.current_server.id if isinstance(server, int) else self.current_server\n\nAttributeError: 'NoneType' object has no attribute 'id'\n"
[D] showError:82 - Python error: Return value of PyObject call is NULL: Traceback (most recent call last):

  File "/usr/share/harbour-saildiscord/python/main.py", line 233, in set_channel
    self.client.set_current_channel(guild, channel)

  File "/usr/share/harbour-saildiscord/python/main.py", line 106, in set_current_channel
    self.run_asyncio_threadsafe(self.get_last_messages(), True)

  File "/usr/share/harbour-saildiscord/python/main.py", line 98, in run_asyncio_threadsafe
    if result_required: return future.result(timeout)

  File "/usr/lib64/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()

  File "/usr/lib64/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception

  File "/usr/share/harbour-saildiscord/python/main.py", line 93, in get_last_messages
    await send_message(m, True)

  File "/usr/share/harbour-saildiscord/python/main.py", line 57, in send_message
    event, args = await generate_message(message, is_history)

  File "/usr/share/harbour-saildiscord/python/main.py", line 37, in generate_message
    if comm.client.ensure_current_channel(message.reference.channel_id, message.reference.guild_id):

  File "/usr/share/harbour-saildiscord/python/main.py", line 123, in ensure_current_channel
    ccs = self.current_server.id if isinstance(server, int) else self.current_server

AttributeError: 'NoneType' object has no attribute 'id'

[2024-12-16 23:22:01] [INFO    ] root: Client was disconnected succsessfully
```

**Comment by roundedrectangle** [comment]
fixed in 0.7
